### ISSUE TITLE
Remove Deferred.asWorker() converter function

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#10]
This converter _looks_ a lot like `Single.asWorker()`, but has a major pitfall: it doesn't scope. This difference is subtle, and might make code hard to reason about: given `foo.asWorker()`, the work will be scoped to the `Worker` if `foo` is a cold future like `Single`, but not if it's a hot future like `Deferred`.

A more theoretical reason is that I think it's bad coroutines practice to expose `Deferred`s as public API because it breaks structured concurrency. We shouldn't encourage that practice by providing this converter.

**Comment by rjrjr** [comment]
This was done.
