### ISSUE TITLE
Un-deprecate runningWorker for LifecycleWorker

### ISSUE THREAD

**Issue by LandonPatmore** [square/workflow-kotlin#1136]
Getting a deprecation warning for:

```kotlin
context.runningWorker(teardownWorker)
```

Which looks like:

```
private val teardownWorker = object : LifecycleWorker() {
  override fun onStopped() {
    mediaPlayer.shutDown()
  }
}
```

The alternative says to use `runningSideEffect`, but it doesn't seem to work and we would need to rewrite `LifecycleWorker`.

**Comment by rjrjr** [comment]
The alternative is to use `SessionWorkflow` and set up a teardown via the `CoroutineScope` passed to `initialState`. The deprecation message needs to be updated.

Keeping this ticket open as a reminder of that.

**Comment by steve-the-edwards** [comment]
I did this here - along with more contextual documentation https://github.com/square/workflow-kotlin/pull/1139
