### ISSUE TITLE
Fix refreshVersions config

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#132]
From [Slack](https://kotlinlang.slack.com/archives/CP5659EL9/p1594493155053100):

> If you go on the develop branch, you'll see the updated README and docs (and you can grab that dev version, it's documented too). There's been a renaming (which I should write the chengelog of this weekend), refreshVersions is/will be the new name for the dependencies plugin, which includes the refreshVersions-core plugin (that one was named refreshVersions before). Also, both versions will be synchronized, it was simpler to manage on my end, and we made the decision to target the Kotlin "niche" by promoting the Kotlin ecosystem targetted dependency constants, while not excluding the rest of the Gradle ecosystem, and allowing to just depend on refreshVersions-core.
> 
> About the sample-android, it has not been updated in a while and isn't taking part in the CI checks for now, but the setup of the sample-multi-modules on the develop branch works perfectly for Android projects, and I use it happily in a 55 modules project.
>

**Comment by rjrjr** [comment]
We ditched refreshVersions.
