### ISSUE TITLE
Investigate RenderTester use for workflows that have operators (e.g. mapRendering) applied to them

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#137]
The operator changes the rendering type, so the test runner needs a way to map the "expected" rendering/output from the expected workflow to the type that the workflow-under-test actually expects, but it can't do that without actually rendering the operator private workflows, which there is no way to create expectations for.

We should at least ensure that we _can_ solve this before stabilizing the API, so that we don't get stuck with a broken API.

cc @dhavalshreyas

**Comment by zach-klippenstein** [comment]
Trying to figure out how to support this in kotlin since we completely fake out the entire renderChild call. Operator workflows are entirely self contained. I think we might have to introduce a nested expectation api for this. E.g. something like
```kotlin
workflow.testRender()
  .expectRenderMapping { it.expectWorkflow(child.identifier) }
```

Where `expectRenderMapping` is implemented by some api like:
```kotlin
fun RenderTester.expectNestedWorkflow(
  identifier: WorkflowIdentifier,
  // RenderTester instance that is used to expect workflows rendered by the child.
  nestedTester: (RenderTester)->Unit
)
```

Or maybe inverted, so
```kotlin
fun RenderTester.expectWorkflow(
  …,
  // Can be passed something that "implements" workflow operators for tests.
  wrapper: (Something) -> Something = {}
)
```

where the `wrapper` thing can recurse, so you can describe `child.mapOutput{}.mapRendering{}`

**Comment by rjrjr** [comment]
Meh.
