### ISSUE TITLE
Buttons on successive AlertScreen renderings are not respected

### ISSUE THREAD

**Issue by christiandeange** [square/workflow-kotlin#138]
When rendering two different `AlertScreen`s in back-to-back render passes, the button contents do not seem to be updated by the `AlertContainer` properly.

| First Rendering | Second Rendering |
|----------------|--------------------|
| <code>AlertScreen(message = "Starting Checkout...", onEvent = {})</code> | <code>AlertScreen(message = "Waiting for checkout...", buttons = mapOf(NEGATIVE to "Cancel"), onEvent = { ... })</code> |
| ![Screenshot_1595382241](https://user-images.githubusercontent.com/3208823/88193018-30950300-cc0b-11ea-8e0e-26727fd755cc.png) | ![Screenshot_1595382242](https://user-images.githubusercontent.com/3208823/88193020-312d9980-cc0b-11ea-9e8d-e2297953ca9f.png) |

At first I was able to work around this locally by using some reflection to manually force the buttons to be re-bound to the UI again:

```
val buttonPanel = dialog.findViewById<ViewGroup>(androidx.appcompat.R.id.buttonPanel)
dialog.javaClass.getDeclaredField("mAlert")
    .let { mAlert ->
      mAlert.isAccessible = true
      mAlert[dialog].javaClass.getDeclaredMethod("setupButtons", ViewGroup::class.java)
          .let { setupButtons ->
            setupButtons.isAccessible = true
            setupButtons(mAlert[dialog], buttonPanel)
          }
    }
```

Eventually I just decided to implement my own `AlertContainer`-like container to subvert this entirely.

**Comment by rjrjr** [comment]
Fixed by #595
