### ISSUE TITLE
WorkflowFragment layout does not render after navigating away and back using Jetpack navigation

### ISSUE THREAD

**Issue by ychescale9** [square/workflow-kotlin#14]
When using the **AndroidX Navigation** library to navigate to a second fragment from a `WorkflowFragment` and navigating back (back press), the `WorkflowLayout` does not render.

I added some breakpoints in `WorkflowLayout` and it seems like the `onViewAttachedToWindow` in `takeWhileAttached` is never invoked when navigating back to the `WorkflowFragment`.

I've [extended the `hello-workflow-fragment` sample](https://github.com/ychescale9/workflow-kotlin/tree/yc/jetpack-nav/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment) to demonstrate this by setting up a simple navigation graph: clicking on a button in `HelloWorkflowFragment` navigates to the `SecondFragment` using `root.findNavController().navigate(R.id.action_helloFragment_to_secondFragment)`.

**Comment by rjrjr** [comment]
Related conversation in Slack: https://workflow-community.slack.com/archives/CHTFPR277/p1592468482119100

Seems like we should do two things:

 1. Create the workflow runner and call `WorkflowLayout#start` in `onCreateView()` itself at which point the view is guaranteed not to be attached.

 2. Edit `View.takeWhileAttached` in `WorkflowLayout` to trigger the callback if the view is already attached to the window before adding the listener, similar to what `View.doOnAttach` from core-ktx does.

Why both? The latter is less surprising and will probably prevent other surprises down the road. The former, doing as much initial work as possible before the view is attached, keeps things consistent and may prevent other problems, esp. around view persistence.

**Comment by rjrjr** [comment]
Hmm. Not actually sure if moving this out of `onViewStateRestored` is an option. Need to test if that would clobber in-flight text editing and such.

**Comment by rjrjr** [comment]
Hurray, view persistence is already broken in both HelloWorkflow and HelloWorkflowFragment. Did the move to Android view binding break it? Maybe it was always broken for simple root views, but masked by `BackStackContainer` in the more complex samples?

Will track that separately. Might get the fix for free-ish from #36. 🤞
