### ISSUE TITLE
Can't compile workflow implementations with Kotlin 1.4 IR backend

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#144]
Caused by a compiler bug: https://youtrack.jetbrains.com/issue/KT-40605

This is triggered by the new inner class `RenderContext`s. This blocks using the Workflow alpha with Compose. 

This affects consumers of this library trying to use the IR backend, this issue has nothing to do with trying to build the Workflow library itself using the IR backend.

**Comment by zach-klippenstein** [comment]
Underlying bug has apparently been fixed in 1.4.20 dev builds.

**Comment by rjrjr** [comment]
@vRallev I've lost track, is this still an issue?

**Comment by vRallev** [comment]
No, couldn't find that you'd opt-out of the IR backend and you're using a Kotlin version that uses it by default.

**Comment by zach-klippenstein** [comment]
Yea this definitely works, or the compose samples would be very broken.
