### ISSUE TITLE
WorkflowInterceptor should get passed the actual instances of the workflows it's intercepting

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#145]
Main use case so far is integration with LeakCanary (discussion [here](https://square.slack.com/archives/CE470RL5T/p1595438886217300?thread_ts=1595431492.211600&cid=CE470RL5T)), although this could be useful for other things, such as tagging workflows with marker interfaces for interceptors to process.

This doesn't block 1.x because this API is already marked as experimental.

Cc @pyricau

**Comment by rjrjr** [comment]
The workflow instance now is passed via `RenderContextInterceptor.onRenderChild`.
