### ISSUE TITLE
If OverviewDetailScreen's "selectDefault" is not null but doesn't update the detail-side, previous rendering will remain in the Detail Screen

### ISSUE THREAD

**Issue by aeshragh** [square/workflow-kotlin#159]
If OverviewDetailScreen's "selectDefault" lambda doesn't update the Detail-side, I notice that Detail-side does not get re-rendered (and the previous rendering that existed there continues to persist). What I expected was for the Detail side to be rendered as a blank-page. I think this may be a bug because if my Detail rendering is null and no "selectDefault" is specified, then the detail-side renders as a blank Page.

**Comment by rjrjr** [comment]
This is not a bug, it's a contract violation. `selectDefault` must not no-op. I'll punch up its kdoc to make that more clear.
