### ISSUE TITLE
RecyclerView's scroll position not restored after config change when using Jetpack navigation

### ISSUE THREAD

**Issue by ychescale9** [square/workflow-kotlin#162]
I'm again trying to integrate workflow with Jetpack navigation / fragment 😅  and found an issue where the `RecyclerView`'s scroll position is not restored after config change.

I've again extended the [`hello-workflow-fragment` sample](https://github.com/ychescale9/workflow-kotlin/tree/yc/jetpack-nav-recyclerview-scroll-position/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment) to reproduce this:

1. Scroll the list so some items at the top are off the screen
2. Rotate the screen
3. The 1st item appears at the top of the list

This can also be reproduced by just using `FragmentViewContainer` to inflate the fragment so this might not necessarily be Jetpack navigation:

```
<androidx.fragment.app.FragmentContainerView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/helloWorkflowFragment"
    android:name="com.squareup.sample.helloworkflowfragment.HelloWorkflowFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".HelloWorkflowFragmentActivity"
    />


```

**Comment by ychescale9** [comment]
Using `renderWorkflowIn` with a `viewModelScope` directly and exposing the returned `StateFlow` to a regular fragment seems work.

**Comment by rjrjr** [comment]
See meaty discussion in Slack inspired by the work around. May repurpose this ticket to look into replacing both `WorkflowFragment` and `Activity.setContentWorkflow` with a single wrapper of `renderWorkflowIn` tied to `SavedStateRegistry` for snapshots.

https://workflow-community.slack.com/archives/CHTFPR277/p1596813762239100
