### ISSUE TITLE
Dialogs isn't dismissed when workflow stops rendering it without interaction on the dialog itself

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#204]
If a workflow renders a dialog with a listener on the buttons that result in the dialog no longer being rendered, everything is fine.

However, if the workflow suddenly stops rendering the dialog _without_ the user having clicked on the dialog buttons, the dialog is not dismissed.

Repro steps:
1. Render a dialog with `AlertContainerScreen`.
2. After a timeout, stop rendering it. Dialog will still be around.

Repro project: https://github.com/square/droidcon-nyc-2019-workflow-game (win the game, then enter time travel mode and scrub past the "game over" dialog)

**Comment by rjrjr** [comment]
Fixed by #595
