### ISSUE TITLE
Can we do better than RenderContext.onEvent?

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#208]
Here's the dream:

```kotlin
    onSplitTenderPressed = context.eventHandler { event -> 
      state = when(event.foo) { ... }
      setOutput(event.blah)
    }
```

I _think_ we can get that done by adding an `EventT` param to `WorkflowAction.Updater`, and `action {}`. That should be palatable if we can provide convenience overloads for when `EventT` is `Unit`, so that existing `action {}` calls don't break. If we can't pull that off, doesn't seem worthwhile.

**Comment by rjrjr** [comment]
@zach-klippenstein I snuck this into the 1.0 milestone mainly to get your attention, don't know that we should really block on it.

I aim to give it a try next week, though.

**Comment by rjrjr** [comment]
I mean, the _real_ dream would be more like this, with an arbitrary set of parameters

```kotlin
  onSplitTenderPressed = context.eventHandler { able, baker -> 
      state = when(able) { ... }
      setOutput(baker)
    }
```

But I can't imagine any way to pull that off.

**Comment by rjrjr** [comment]
Oh, and more realisitcally, the state references will all be more like `this@eventHandler.state =`. Maybe that's enough to make us just stick with today's `onEvent`.

**Comment by rjrjr** [comment]
It’s actually really easy to make this work, even with a (fairly) arbitrary number of event parameters.

```kotlin
SelectTenderScreenData(
    doTheThing = context.eventHandler { able, baker, charlie ->
      setOutput(able + baker + charlie)
    },
    onSplitTenderPressed = context.eventHandler {
      setOutput(SplitTenderSelected)
    }
)
```

The wrinkle is that updating the state requires use of `this`. And really you should read it that way to, to avoid picking up stale state from the param passed to the `render` call.

```kotlin
  override fun render(
    props: Unit,
    state: State,
    context: RenderContext
  ): Rendering {
    return Rendering(
        message = "$state",
        onClick = context.eventHandler {
          this.state = when(this.state) {
            Able -> Baker
            Baker -> Charlie
            Charlie -> Able
          }
        },
        onBackPressed = if (state == Able) null else context.eventHandler {
          this.state = when(this.state) {
            Able -> throw IllegalStateException()
            Baker -> Able
            Charlie -> Baker
          }
        }
    )
  }

```

The good news is that the compiler will force the `this.` on the LHS, and in theory we can 
provide a lint check to enforce it on the RHS.

```kotlin
// vvvv - required to compile
   this.state = when(this.state) { ... }
//                   ^^^^ - lint check I hope.    
```

So…want it?

**Comment by zach-klippenstein** [comment]
Sure, looks as good to me as anything we have now 😅

**Comment by Blisse** [comment]
any thoughts around making some convenience helpers like 

```
val currentState: State get() = state
var nextState: State set(value) = this.state = value 
```

so we can do 

```
nextState = when (currentState) { … }
```

**Comment by Blisse** [comment]
Also, asked in # kotlin, but is it possible to use `@DslMarker` from https://kotlinlang.org/docs/reference/type-safe-builders.html#scope-control-dslmarker-since-11 to prevent (implicit) access of the outer state?

**Comment by zach-klippenstein** [comment]
Nope, `DslMarker` is only for receivers, and the state passed to `render` isn't a receiver.

We could move props, state, & context to be passed in through a receiver object, which would probably let us do this, and also reduce a lot of boilerplate.

**Comment by rjrjr** [comment]
> any thoughts around making some convenience helpers like
> 
> ```
> val currentState: State get() = state
> var nextState: State set(value) = this.state = value 
> ```
> 
> so we can do
> 
> ```
> nextState = when (currentState) { … }
> ```

So `currentState` is sticky. That's kind of neat. I'd normally shy away from that kind of thing, but it's tempting here.

**Comment by rjrjr** [comment]
> Nope, `DslMarker` is only for receivers, and the state passed to `render` isn't a receiver.
> 
> We could move props, state, & context to be passed in through a receiver object, which would probably let us do this, and also reduce a lot of boilerplate.

Gonna play with that, just to see what it's like. I think we can get there in a backward compatible way.

**Comment by rjrjr** [comment]
Whoa. @zach-klippenstein, @Blisse, check out the second commit on this PR. Sketches out `abstract fun RenderContext.render(): RenderT`. All the probems go away.

I think we should do this.

https://github.com/square/workflow-kotlin/pull/212/commits/47fb3de3ae5368f0fc1d9e79b27a1c02cdc8d508

**Comment by rjrjr** [comment]
Only question in my mind is how this plays out w/ the syntax for binding workers to actions.

**Comment by rjrjr** [comment]
Thinking we can provide parallel overloads to `runningWorker` that take various `Updater.(EventT) -> Unit` lambdas; and overloads to `eventHandler` that take `(EventT) -> WorkflowAction` lambdas. So both styles work for both cases — inline actions and external actions.

**Comment by zach-klippenstein** [comment]
FYI the PR is #212.

**Comment by rjrjr** [comment]
> Thinking we can provide parallel overloads to `runningWorker` that take various `Updater.(EventT) -> Unit` lambdas; and overloads to `eventHandler` that take `(EventT) -> WorkflowAction` lambdas. So both styles work for both cases — inline actions and external actions.

Doing that via overloads makes the `runningWorker` and `eventHandler` methods ambiguous. Uninspired an alternative names.

**Comment by rjrjr** [comment]
Tracking the _RenderContext as receiver_ notion separately, #213. Will land a proper PR with just the `eventHandler` changes.

**Comment by rjrjr** [comment]
@Blisse with #213 on the horizon, I don't want to add `currentState` and `nextState`.

**Comment by Blisse** [comment]
> @Blisse with #213 on the horizon, I don't want to add `currentState` and `nextState`.

Makes sense to me 👍
