### ISSUE TITLE
Snapshot laziness is broken by RenderingSnapshot.equals

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#223]
I suspect that this call in `renderWorkflowIn` has broken it:

```kotlin
      // After receiving an output, the next render pass must be done before emitting that output,
      // so that the workflow states appear consistent to observers of the outputs and renderings.
      renderingsAndSnapshots.value = runner.nextRendering()
```
b/c of a call to `equals` in `StateFlowImpl`

![Screen Shot 2020-10-27 at 10 23 56 AM](https://user-images.githubusercontent.com/1884445/97339823-47697800-1840-11eb-8426-081c7d6d8b7c.png)

Should be a simple fix, make `RenderingAndSnapshot.equals` and `hashCode` ignore the `Snapshot`.

https://workflow-community.slack.com/archives/CHTFPR277/p1603819369039000

**Comment by zach-klippenstein** [comment]
Pretty sure we have tests for this somewhere, but they might not be at the right level.

**Comment by rjrjr** [comment]
It's proving hard to write a unit test for this — we're swallowing exceptions thrown by the Snapshot. And for "we're", might have to read "StateFlowImpl is".

**Comment by rjrjr** [comment]
Worked around that, tracking it separately.
