### ISSUE TITLE
Can't use WorkflowViewStub as root item views in RecyclerViews

### ISSUE THREAD

**Issue by bnvinay92** [square/workflow-kotlin#229]
WorkflowViewStub#show() requires a parent view but Recyclerview#onBindViewHolder gets called before views are added to the Recyclerview.

**Comment by zach-klippenstein** [comment]
We might have just hit this [internally](https://square.slack.com/archives/CE470RL5T/p1608057862048700?thread_ts=1608057096.046000&cid=CE470RL5T).

**Comment by rjrjr** [comment]
> We might have just hit this internally

We didn't. This would be a deep, fundamental change to the `WorkflowViewStub` contract, I don't see it happening -- especially since the work around is as simple as putting a `FrameLayout` or something in place to host the stub.
