### ISSUE TITLE
about the BottomNavigationView.

### ISSUE THREAD

**Issue by Alvazz** [square/workflow-kotlin#257]
In our project, we are going to use BottomNavigationView to do page jumps. Is this support? It's not just a few Fragments, but about multiple back stacks. In addition, for example, Fragment jumps (i.e. a new Fragment page pops up, and the new page does not have a BottomNavigationView.), I know a lot. This seems very difficult to achieve. I am looking forward to the realization of workflow.

**Comment by rjrjr** [comment]
While workflow is intended as an alternative to fragments and the new navigation system, I don't see any reason that `WorkflowFragment` wouldn't work with them. But we also don't have any experience with them, so you'd be pioneering.

If you decide to try it out, we'll be grateful to hear about your experience.

**Comment by Alvazz** [comment]
thanks.
