### ISSUE TITLE
Publish :workflow-core as multiplatform library

### ISSUE THREAD

**Issue by bnvinay92** [square/workflow-kotlin#336]
Current blockers:

- Remove the use of reflection to restore `WorkflowIdentifier`
- Bump okio
- A couple of `java.lang.Float` invocations

**Comment by NickvanDyke** [comment]
May I ask what priority this is, or an estimation of the workload/timeline? I'm starting a new project soon and would love to develop it with this in mind, then take advantage of it once completed.

Would more work be needed after this issue, or would you then just use workflow-swift to connect the common Kotlin workflows to the iOS UI?

**Comment by rjrjr** [comment]
I'm afraid multiplat support is all in the realm of "contributions welcome," we're not working on it actively.

**Comment by rjrjr** [comment]
Keep in mind, though, that the Swift and Android flavors of workflow have _very_ similar APIs. At Square it's common for our Android and iOS teams to design their features together, and build parallel workflow classes.

**Comment by rjrjr** [comment]
Touchlab has started taking a crack at it! Closing this ticket in favor of #552.
