### ISSUE TITLE
View persistence is broken in both HelloWorkflow and HelloWorkflowFragment.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#38]
Did the move to Android view binding break it? Maybe it was always broken for simple root views, but masked by `BackStackContainer` in the more complex samples?

To demonstrate, add an `EditText` (with id!) to the layout file, and type in it. The text you enter will survive config change, but not process death.

Might get the fix for free-ish from #36. 🤞

_Originally posted by @rjrjr in https://github.com/square/workflow-kotlin/issues/14#issuecomment-648449307_

**Comment by rjrjr** [comment]
Yes, fixed by #36

**Comment by morris23-desin** [comment]
> Did the move to Android view binding break it? Maybe it was always broken for simple root views, but masked by `BackStackContainer` in the more complex samples?
> 
> To demonstrate, add an `EditText` (with id!) to the layout file, and type in it. The text you enter will survive config change, but not process death.
> 
> Might get the fix for free-ish from [#36](https://github.com/square/workflow-kotlin/issues/36). 🤞
> 
> _Originally posted by [@rjrjr](https://github.com/rjrjr) in [#14 (comment)](https://github.com/square/workflow-kotlin/issues/14#issuecomment-648449307)_
