### ISSUE TITLE
Move WorkflowFragment out to samples and / or test it properly

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#40]
Related to #39, #14, #38.

**Comment by rjrjr** [comment]
I'm actually kind of torn about this. We don't and won't use `WorkflowFragment` in production, but It seems absolutely required for incremental adoption — witness the bug reports from @bnvinay92 and @ychescale9.

**Comment by zach-klippenstein** [comment]
Since #55 is going to mark all our UI integration as experimental, this issue doesn't need to be in the 1.0 milestone.
