### ISSUE TITLE
DecorativeViewFactory should support wrapping Context

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#413]
This is about the only thing it doesn't support, but I need it for wrapping the context at the root.

**Comment by rjrjr** [comment]
Also handy just for reading things from the Context, e.g. to populate the ViewEnvironment from it.

**Comment by rjrjr** [comment]
Might be less crazy making to do this with a separate decorator. The tricky bit is that the `map` function, `(OuterT, ViewEnvironment) -> Pair<InnerT, ViewEnvironment>`, gets run twice:

- when we're building the view
- when we update the view

So we don't want to change the function to:

```kotlin
(OuterT, ViewEnvironment, Context) -> Triple<InnerT, ViewEnvironment, Context>
```

because the Context transformation is only useful at build time, it would be wasted effort when updating.

**Comment by rjrjr** [comment]
And if a separate wrapper makes sense for `Context` transformations, maybe `ViewEnvironment` swizzling should move there too. We hardly ever use it, and when we do it's pretty confusing. Gonna look at current uses…

**Comment by rjrjr** [comment]
Well poo. This actually isn't useful for seeding the `ViewEnvironment` with values from the `Context`, which is what made me dust off this issue. There isn't easy enough access to the `Context` on updates. Putting it back in the icebox.

**Comment by rjrjr** [comment]
This will be addressed by #606

**Comment by rjrjr** [comment]
> This will be addressed by #606

Nope, that didn't work out.

**Comment by rjrjr** [comment]
Possible better solution from @helios175:

```kotlin
fun <T : Any> ViewFactory<T>.wrapContext(
  type: KClass<T>,
  wrapContext: (ViewEnvironment, Context) -> Context
): ViewFactory<T> {
  val original = this
  return object : ViewFactory<T> {
    override val type: KClass<in T> = type

    override fun buildView(
      initialRendering: T,
      initialViewEnvironment: ViewEnvironment,
      contextForNewView: Context,
      container: ViewGroup?
    ): View {
      val adjustedContext = wrapContext(initialViewEnvironment, contextForNewView)
      return original.buildView(initialRendering, initialViewEnvironment, adjustedContext, container)
    }
  }
}
```

**Comment by rjrjr** [comment]
Be nice to replace `DecorativewScreenViewFactory` w/a set of extensions like this. At least make it non-public API.

**Comment by rjrjr** [comment]
That snippet might be naive about the requirements for `LayoutInflater`, though. See https://github.com/square/mortar/blob/master/mortar/src/main/java/mortar/MortarScope.java#L41

**Comment by rjrjr** [comment]
`ScreenViewFactory` supports that easily.
