### ISSUE TITLE
Consider how to use KEEP-259 to improve ViewRegistry API

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#440]
https://github.com/Kotlin/KEEP/issues/259 proposes introducing syntax and semantics for multiple receivers in kotlin. This is the evolution of earlier discussions to support type classes. 

For workflows, we had been eagerly awaiting type classes because it would let us change the ViewRegistry to be something that could be validated at compile time instead of runtime. Swift workflows already do this, using Swift's extension protocols.

While KEEP-259 is less powerful than the initial type class proposal, it may still be something we can leverage.

_This discussion was initially started by @rjrjr on [Twitter](https://twitter.com/rjrjr/status/1405972122187403265?s=21)._

**Comment by zach-klippenstein** [comment]
I don't think there is necessarily very much interesting to explore here. We can get compile safety but just defining view factories as extension functions on renderings. This works very well in compose, and it's probably not worth trying to solve for Android views anymore.

**Comment by rjrjr** [comment]
Obsolete.
