### ISSUE TITLE
WorkflowContainer not available from Maven

### ISSUE THREAD

**Issue by atonamy** [square/workflow-kotlin#442]
Also beta version is not available from Maven Central.
Maximum available version  is 1.0.0-alpha14 and workflow-ui-core-compose only available 0.30.0 where is no  WorkflowContainer.
How to fix it? How to fetch latest version from Maven Central which is available on GitHub without importing manually source code?

**Comment by rjrjr** [comment]
We don't yet consider the compose integration stable enough to ship against, but stay tuned.

We haven't released a beta yet.
