### ISSUE TITLE
Start running UI tests on tablet emulators in CI

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#501]
We have things that will break on tablets, but not phones.

**Comment by rjrjr** [comment]
Added the compose label b/c the broken things are related to SavedStateRegistry, the need for which is fundamentally driven by Compose support.

**Comment by rjrjr** [comment]
IIRC, it's the To Do app that is broken.

**Comment by rjrjr** [comment]
#553 is close enough. We don't especially need tablets, just landscape.
