### ISSUE TITLE
Move ViewEnvironment into workflow-ui/core-common

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#52]
It has no Android dependencies, it's entirely self-contained. Should probably review other code in this module as well to make sure it's in the right place.

**Comment by zach-klippenstein** [comment]
Since #55 is going to mark all our UI integration as experimental, this issue doesn't need to be in the 1.0 milestone.

**Comment by rjrjr** [comment]
Fixed by #591.
