### ISSUE TITLE
Samples and tutorial are out of date?

### ISSUE THREAD

**Issue by Kernald** [square/workflow-kotlin#532]
The Android samples and tutorial are using `setContentWorkflow`, which has been deprecated a while ago in #266 (and now removed in #514).

**Comment by rjrjr** [comment]
Yeah, that seems important. Thanks.

**Comment by Kernald** [comment]
@rjrjr sorry I didn't look in-depth enough, I was referring to both the documentation of the tutorial and the implementation in the samples folder. Thanks for the quick fix here!
