### ISSUE TITLE
Is `NamedViewFactory` included automatically or isn't it?

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#538]
https://workflow-community.slack.com/archives/CHTFPR277/p1630599181038900?thread_ts=1630549583.028900&cid=CHTFPR277

**Comment by rjrjr** [comment]
@lucamtudor Looks like `WorkflowLayout#start` is where we ensure that `NamedViewFactory` is in play. Were you using that?

**Comment by lucamtudor** [comment]
@rjrjr I'm using the new `workflow.renderAsState()`

**Comment by rjrjr** [comment]
Sweet. Okay, we should fix that. Noted.

**Comment by rjrjr** [comment]
`WorkflowRendering` is probably the right spot. And should probably move the existing line from `WorkflowLayout` to `WorkflowViewStub`.
