### ISSUE TITLE
Introduce TextController

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#554]
https://gist.github.com/rjrjr/912d50bd1b5a3348f19e7ea521f21b8b

Should be the fix for #414, #384

**Comment by lucamtudor** [comment]
I just realised I managed to run with Workflow for like 3 months without a single EditText (actually without Compose's TextField).

**Comment by rjrjr** [comment]
They're only a problem if you want the workflow in the loop character by character as you type. It's just not practical for the workflow to be the source of truth in that situation. With TextController, we leave the android classes in control, while still making it possible for the workflow to peek at what's going on. We expect you'll use conventional formatters, etc.
