### ISSUE TITLE
Delete legacy modules

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#6]
We're not going to be able to delete this anytime soon, and that should definitely not block 1.0. We could pull them out into a separate repo, but that would just make more work for us. We could leave them here and stop releasing new artifacts for them, but we might run into issues as they fall behind on dependencies like coroutines and kotlin. We could just keep them going publishing 0.x releases, but it's already too late for that, since we pushed the 1.0.0-alpha.1 release. We could keep them in alpha, even after the other artifacts graduate to beta/release, but we'll need to do some surgery on our build scripts.

@rjrjr WDYT?

_Originally posted by @zach-klippenstein in https://github.com/square/workflow/issues/548#issuecomment-643653257_

**Comment by zach-klippenstein** [comment]
I think it's probably cleanest to just delete these from github and copy them into our internal codebase until we can delete for good.

**Comment by rjrjr** [comment]
I completely agree. We've done that a couple of times already and it's no big deal.
