### ISSUE TITLE
WorkflowLifecycleOwner leaks if WorkflowLayout is the content view of a dialog

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#610]

**Comment by rjrjr** [comment]
Recipe is something like:

- A `WorkflowLayout` is the content view for a `Dialog` instead of an `Activity`
- The dialog window is closed
- `destroyOnDetach` is never called by the `WorkflowViewStub` in the `WorkflowLayout`
- LeakCanary reports something like _Activity Lifecycle > WorkflowLifecycleOwner > WorkflowLayout_ as a leak, because the `WorkflowLayout` has been detached from its window but the Activity still has a reference to it.

Not sure of the exact fix. Maybe as simple as `WorkflowLayout` calls `WorkflowLifecycleOwner.install(this).destroyOnDetach()` in its `doOnAttach`?

Have to remember why we don't do that by default for every view.

**Comment by MohitMandalia** [comment]
HI @rjrjr ,

Can I get some issue to work with I am new here.

Thanks

**Comment by rjrjr** [comment]
Hi @MohitMandalia, thanks for your interest. There are a few [issues tagged with _good first issue_](https://github.com/square/workflow-kotlin/labels/good%20first%20issue), does that help?

**Comment by MohitMandalia** [comment]
Okay @rjrjr  Thanks will check them.

**Comment by rjrjr** [comment]
> Have to remember why we don't do that by default for every view.

We don't do it on default because that would defeat the whole purpose of `ViewTreeLifecycleOwner`, which is to reflect the lifetime of the container, typically an `Activity` for `Fragment` instance. In this case, whatever code is in charge of managing the `Dialog` and eventually retiring must be reponsible for calling `destroyOnDetach()` when it knows that the `Dialog` will never be shown again. We can't automate that.
