### ISSUE TITLE
nextRendering() is called in runtime if Workflow's scope is cancelled.

### ISSUE THREAD

**Issue by steve-the-edwards** [square/workflow-kotlin#642]
Right now in `renderWorkflowIn` we check if the `CoroutineScope` `isActive` at the top of the loop:

```
  scope.launch(start = ATOMIC) {
    while (isActive) {
      // It might look weird to start by consuming the output before getting the rendering below,
      // but remember the first render pass already occurred above, before this coroutine was even
      // launched.
      val output = runner.nextOutput()

      // After receiving an output, the next render pass must be done before emitting that output,
      // so that the workflow states appear consistent to observers of the outputs and renderings.
      renderingsAndSnapshots.value = runner.nextRendering()
      output?.let { onOutput(it.value) }
    }
  }
```

But since `nextOutput()` is suspending we could resume and have had an `action` `cancel()` the `CoroutineScope` of the root workflow. We should pro-actively check this before calling `nextRendering()`.

Something like:

```
  scope.launch(start = ATOMIC) {
    while (isActive) {
      // It might look weird to start by consuming the output before getting the rendering below,
      // but remember the first render pass already occurred above, before this coroutine was even
      // launched.
      val output = runner.nextOutput()

      if (!isActive) return@launch
      // After receiving an output, the next render pass must be done before emitting that output,
      // so that the workflow states appear consistent to observers of the outputs and renderings.
      renderingsAndSnapshots.value = runner.nextRendering()
      output?.let { onOutput(it.value) }
    }
  }
```

**Comment by rjrjr** [comment]
As part of this conversation, we were also questioning the need for `start = ATOMIC`. Seems like it might be vesitigal at this point, and that we should just use `DEFAULT`.

**Comment by steve-the-edwards** [comment]
@zach-klippenstein any reason you can think of not to do this? It came up because we had a `WorkflowInterceptor` in PoS that had an `invokeOnCompletion` listener on the Workflow's scope and cleared out resources at that time but then `onRender()` was still called one more time.

**Comment by steve-the-edwards** [comment]
> As part of this conversation, we were also questioning the need for `start = ATOMIC`. Seems like it might be vesitigal at this point, and that we should just use `DEFAULT`.

Ya am covering this in #643 as its a slightly different matter.
