### ISSUE TITLE
Are multiple state changes / output emissions propagated together (result in 1 render pass, or multiple)?

### ISSUE THREAD

**Issue by zoltish** [square/workflow-kotlin#660]
Sorry, I couldnt think of a good title for this, and perhaps this is a terrible place to ask about this. 

What Im basically wondering is whether or not multiple state changes & output emissions in one render pass are "combined" such that the tree is only re-rendered once? 

As an example;

`Workflow A` is at the root, and renders `Workflow B`. After some time, B emits an output which results in A adjusting its state. Both of these events happen "at the same time". Do they result in 2 re-renders, 1 for the output, and 1 for the state change, or are they propagated together such that the tree is only re-rendered once?

**If they are propagated together**, how do you make that happen? This is a concept Im trying to deepen my understanding of with coroutines and since Ive experimented a bunch with your library in the past it came to mind. Im fairly fluent in most of kotlin & coroutines, but this particular subject (if it even works that way) escapes me almost entirely. From my point of view, each channel will lead to a new event (be it state change, or an output) and the root will receive 2 events regardless. 

If theres another place I might better ask this, please let me know. Thanks for your time!

**Comment by rjrjr** [comment]
We have https://github.com/square/workflow-kotlin/discussions, but no one ever finds that so 🤷 

The latter, we don't re-render until the outputs are all handled. The entire workflow tree effectively has one big combined state which gets updated atomically, and then the next render pass happens.

I believe the key is in `WorkflowNode.applyAction`, where an action is executed and then its output is synchronously passed into `emitOutputToParent()`. That lands in the `acceptChildOutput` function on line 161 of `SubtreeManager`, which calls `emitActionToParent()`, which makes the next recursive call to `WorkflowNode.applyAction`. That's all synchronous.

**Comment by zoltish** [comment]
Thanks for the explanation @rjrjr! Im impressed by the engineering & thought that went into making all of that happen synchronously in one go! Ill redirect any further requests into the discussions section, I was actually aware of its existence when posting this (I swear Im a good person) but the issue tracker seemed like a better spot for this at the time!
