### ISSUE TITLE
[kotlin] WorkflowViewStub breaks view back handling

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin#763]
If a `LayoutRunner` that is being used to render a view inside a `WorkflowViewStub` calls `backPressedHandler =` on the root view (the view passed to the `LayoutRunner`'s constructor), that view is actually the parent view of the stub, so the back handler will be set on the stub's container. If another view doesn't replace the back handler in the stub's container, that handler will live beyond the lifetime of that screen.

To repro, see square/workflow#873.

**Comment by rjrjr** [comment]
That was a flat out bug in the linked PR, should have been setting it on `WorkflowViewStub.actual` if that was the desired behavior.
