### ISSUE TITLE
1.8.0-beta01 breaks compatibility, NoSuchMethodError ViewRegistry

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#796]
Reported by @SalvatoreT:

> Someone is including the 1.8.0-beta01 and the SDK I work on which doesn’t use the beta. Their app throws this error (which I can reproduce).
>
> ```
> java.lang.NoSuchMethodError: No static method ViewRegistry([Lcom/squareup/workflow1/ui/ViewFactory;)Lcom/squareup/workflow1/ui/ViewRegistry; in class Lcom/squareup/workflow1/ui/ViewRegistryKt; or its super classes (declaration of 'com.squareup.workflow1.ui.ViewRegistryKt'
> ```

https://workflow-community.slack.com/archives/CHTFPR277/p1652992917547019

Looks like [this commit](https://github.com/square/workflow-kotlin/commit/3f2f344182dba649061abfe329014e26c42302af#diff-623e17a6bfe9cae052ceb90ecf711847c80149ce0935f15dbeace2d6f50c8a30L105) from #577.

**Comment by rjrjr** [comment]
So, uh…hey @SalvatoreT. I forgot all about this, doubt I did anything about it. Close as obsolete?

**Comment by SalvatoreT** [comment]
Yep, I totally forgot. Closing it makes sense.
