### ISSUE TITLE
ComposeViewTreeIntegrationTest#composition_is_restored_in_modal_after_config_change failing

### ISSUE THREAD

**Issue by steve-the-edwards** [square/workflow-kotlin#800]
Consistently failing on both Pixel 5 emulator API 32 and real physical Pixel 6 API 32.

Tested with animation enabled and disabled on emulator.

```
java.lang.IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
at androidx.savedstate.SavedStateRegistry.consumeRestoredStateForKey(SavedStateRegistry.java:77)
at androidx.compose.ui.platform.DisposableSaveableStateRegistry_androidKt.DisposableSaveableStateRegistry(DisposableSaveableStateRegistry.android.kt:75)
at androidx.compose.ui.platform.DisposableSaveableStateRegistry_androidKt.DisposableSaveableStateRegistry(DisposableSaveableStateRegistry.android.kt:54)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:105)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
```

**Comment by rjrjr** [comment]
I'm seeing the same on Pixel 2 / API 31 AVD. How is CI green?

**Comment by rjrjr** [comment]
Seems like it's introduced by v1.8.0-beta01, which makes sense.

**Comment by rjrjr** [comment]
On the other hand…how was I able to build that release?

**Comment by rjrjr** [comment]
Bisecting. Look what I found on the "good" version:

```
  @Ignore("https://github.com/square/workflow-kotlin/issues/504")
  @Test fun runtimeIsCancelledWhenCompositionFails() {
```

**Comment by rjrjr** [comment]
I deleted that `@Ignore` in https://github.com/square/workflow-kotlin/commit/3633994eb69ed01947d8ff0d469a924c4c6ddbbe, perhaps because I noted that the Compose bug from #504 (https://issuetracker.google.com/issues/197442069) is now marked fixed?

**Comment by rjrjr** [comment]
Nope nope, that change was already in place on `v1.7.0`, the test passes there. Perhaps it was still commented out in my long lived UI overhaul branch so I didn't notice I'd broken it. Going to bisect more carefully.

**Comment by rjrjr** [comment]
git bisect says this is the bad commit: https://github.com/square/workflow-kotlin/commit/e5b5ba9e8aac6c0ddc7326d16635d6c7f5bc18f8

I still don't understand why I didn't see it at the time.

**Comment by rjrjr** [comment]
Oh, interesting: there are now two flavors of this test, one in `LegacyComposeViewTreeIntegrationTest`, and the other a fork of that in `ComposeViewTreeIntegrationTest`. It's the new one (non-Legacy) that's failing.

**Comment by rjrjr** [comment]
The most interesting change in that test is using `BodyAndModalsContainer` instead of `ModalViewContainer`. Likely to be a legitimate bug, on a path we're not yet exercising in production.

**Comment by rjrjr** [comment]
Walking line by line through the old `ModalViewContainer` and the `BodyAndModalsContainer` that replaces it, trying to see where they differ. Looks like the crash comes before we ever make the dialog, which is very unexpected.

**Comment by rjrjr** [comment]
Aha! Confirmed that the broken test, `ComposeViewTreeIntegrationTest#composition_is_restored_in_modal_after_config_change` passes on API 29. It fails on 31 and 32, haven't tried 30 yet.

@zach-klippenstein I wonder if we're going to find another Compose bug in here after all.

**Comment by rjrjr** [comment]
Just found a big difference between the tests. Legacy is initialized showing a dialog, new fork isn't.

**Comment by rjrjr** [comment]
Worth noting that `TestComposeRendering` is a hacky, test-specific alternative to `ComposeRendering` / `ComposeScreen`, not sure it's worth digging in.

**Comment by rjrjr** [comment]
All the other `TestModal` sites in the test look fine.
