### ISSUE TITLE
Avoid recreating `RenderContext` so that the `actionSink` captured in lambdas can be memoized

### ISSUE THREAD

**Issue by steve-the-edwards** [square/workflow-kotlin#849]
Right now the Recomposer sees a different object each time and will force recomposition.

**Comment by rjrjr** [comment]
Seems like we could still have them pass out the same / equal object from actionSink instead of this, rather than avoid the recreation entirely. Could be simpler.

**Comment by steve-the-edwards** [comment]
Fixed by #850
