### ISSUE TITLE
Extend `WorkerTester` API to allow passing in a `TestDispatcher` or `TestScheduler`

### ISSUE THREAD

**Issue by steve-the-edwards** [square/workflow-kotlin#910]
This is to enable skipping of delays and controlling of virtual time.

Such as for:

```
worker.test {
  this.advanceTimeBy(..) <-----------
  assertThat(nextOutput()).isEqualTo(..)
}
```

**Comment by darshanparajuli** [comment]
Should we also consider what the default behavior should be for skipping delays? I wonder if most use cases would want delays to be skipped. We could make it an opt-in functionality to make it not skip the delays, and let the user control the virtual time.
```kotlin
worker.test(skipDelays = false) {
}
```
Not sure if it'll break existing tests though.
