### ISSUE TITLE
Allow `runningWorker` / `renderChild` handlers to return null and avoid re-render.

### ISSUE THREAD

**Issue by rjrjr** [square/workflow-kotlin#915]
The only way a handler can no-op is by returning `noAction()` or equivalent, which means every time any worker or child workflow fires a render pass must happen. We've talked about noticing when state and output are not changed, and avoiding re-render at that point, but defining "changed" is daunting, and it's very late in the game for such a semantic shift. But allowing an explicit `null` return should be easy and safe.

Should deprecate `noAction()` at the same time.

**Comment by rjrjr** [comment]
I wonder if we can go deeper in this direction. E.g., can we instrument `WorkflowAction.Updater.state` such that if `state =` is not called; and the parent consuming `output` returns a `null` action; we short circuit in that case too.

**Comment by steve-the-edwards** [comment]
Covered by #985  and fixed by #992
